export const jsonData = {
    cards: [
        {
            id: 1,
            title: "Lingua Boost",
            desc: "<i>Stack</i>: <b>Vue 3 / Tailwind / Vite &#10155;</b>",
            descLang: "ru-Ru",
            dataDesc: "Проект в разработке.",
            dataLang: "ru-Ru",
            img: "/images/card/vue-es-lp.png",
            imgAlt: "Lingua Boost",
            svgIcon: "icon-vue",
            gitHub: "https://github.com/it2konst/es-lp",
            liveSite: "https://es-lp.vercel.app",
        },
        {
            id: 2,
            title: "Vue Sneakers",
            desc: "<i>Stack</i>: <b>Vue 3 / Tailwind / Vite &#10155;</b>",
            dataDesc: "Development of the Vue Sneakers online store (fetches data from server).",
            img: "/images/card/vue-sneakers.png",
            imgAlt: "Sneakers",
            svgIcon: "icon-vue",
            gitHub: "https://github.com/it2konst/vue-sneakers",
            liveSite: "https://vue-sneakers-rho-brown.vercel.app",
        },
        {
            id: 3,
            title: "Технопрофи",
            desc: "<i>Stack</i>: <b>HTML / SCSS / JavaScript &#10024;</b>",
            descLang: "en-En",
            dataDesc: "Часть коммерческого проекта выложенного в репозитории для портфолио.",
            dataLang: "ru-Ru",
            img: "/images/card/html5-technoprofi.png",
            imgAlt: "Технопрофи",
            svgIcon: "icon-html5",
            gitHub: "https://github.com/it2konst/technoprofi",
            liveSite: "https://it2konst.github.io/technoprofi",
        },
        {
            id: 4,
            title: "Portfolio Website",
            desc: "<i>Stack</i>: <b>HTML / SCSS / JavaScript &#10024;</b>",
            descLang: "en-En",
            dataDesc: "Адаптивный веб-сайт, разработанный с использованием SCSS и JavaScript.",
            dataLang: "ru-Ru",
            img: "/images/card/html5-portfolio-website.png",
            imgAlt: "Portfolio Website",
            svgIcon: "icon-html5",
            gitHub: "https://github.com/it2konst/site-portfolio",
            liveSite: "https://it2konst.github.io/site-portfolio",
        },
    ],
};
